"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _routines_page from './routines-page.bones.json'

registerBones({
  "routines-page": _routines_page,
})
